# Generated by Django 4.0.6 on 2023-12-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_profile_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='slug',
            new_name='description',
        ),
    ]
