# Generated by Django 4.0.6 on 2023-12-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_blogpost_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='description',
            new_name='slug',
        ),
    ]
